-- return {
--   'jose-elias-alvarez/null-ls.nvim',
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--   },
--   opts = function(_, opts)
--     local null_ls = require 'null-ls'
--     opts.sources = {
--       null_ls.builtins.formatting.stylua,
--       null_ls.builtins.formatting.eslint_d,
--       null_ls.builtins.completion.spell,
--       null_ls.builtins.formatting.prettierd,
--       null_ls.builtins.formatting.rustfmt,
--     }
--   end,
-- }
